apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: template-java-apache-camel-fuse-api-v1.0
  title: Template Camel Fuse API v1.0
  description: Plantilla para microservicios en RH Fuse mejorado
  tags:
    - java-apache-camel
  
spec:
  owner: group:Arquitectura
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    
    - title: Datos Repositorio
      required:
        - name
        - description
        - namespace
        - organization
        - project
        - train

      properties:
        name:
          title: Repositorio
          type: string
          description: Nombre único del repositorio
          pattern: '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          ui:autofocus: true

        description:
          title: Descripción
          type: string
          description: Finalidad y/o funcionalidad del componente

        namespace:
          title: Namespace
          type: string
          description: Nombre del espacio asignado al componente
          enum:
          - kernel

        organization:
          title: Organización
          type: string
          description: Organización propietaria del repositorio
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Group
              spec.type: celula

        train:
          title: Tren
          type: string
          description: Tren al que pertenece el repositorio
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Group
              spec.type: tren
 
        project:
          title: Proyecto
          type: string
          description: Proyecto al que pertenece el repositorio
          enum:
          - telefonica-kernel

    - title: Datos AzureDevOps
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com

    - title: Datos Gobierno
      required:
        - platform
        - integration
        - segment
        - product
        - fdomain

      properties:

        consumer:
          title: Consumidores
          type: array
          description: Componente(s) de origen que consume(n) el servicio
          items:
            type: string
            ui:field: EntityPicker
            ui:options:
              catalogFilter:
                kind: Component
          uniqueItems: true
          ui:widget: checkboxes

        destination:
          title: Productores
          type: array
          description: Componente(s) de destino que usa el servicio
          items:
            type: string
            ui:field: EntityPicker
            ui:options:
              catalogFilter:
                kind: Component
          uniqueItems: true
          ui:widget: checkboxes
       
        platform:
          title: Plataforma Despliegue
          type: string
          description: Plataforma donde se desplegara el servicio
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Resource

        integration:
          title: Integración
          type: string
          description: Servicio se puede reusar o es propietario
          enum:
          - reuso
          - sin-reuso
          - reuso-con-aprobacion

        segment:
          title: Segmento
          type: string
          description: Segmento de negocio asociado el servicio
          enum:
          - b2b
          - b2c
          - convergente

        product:
          title: Producto
          type: string
          description: Producto asociado al servicio
          enum:
          - fijo
          - movil
          - convergente
          - productos-digitales
          - productos-robustos-b2b

        fdomain:
          title: Dominio Funcional
          type: string
          description: Linea de servicio asociada al componente
          enum:
          - pagos
          - recargas
          - aprovisionamiento
          - facturacion 
        
        internet:
          title: Visibilidad Desde Internet
          type: boolean
          description: Visibilidad desde internet
          ui:widget: radio

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{parameters.description }}
          namespace: ${{parameters.namespace }}
          organization: ${{parameters.organization }}
          repoUrl: ${{ parameters.repoUrl }}
          segment: ${{ parameters.segment }}
          product: ${{ parameters.product }}
          fdomain: ${{ parameters.fdomain }}
          integration: ${{ parameters.integration }}
          platform: ${{ parameters.platform }}
          consumer: ${{ parameters.consumer }}
          destination: ${{ parameters.destination }}
   
    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: This is ${{parameters.name}}
        repoUrl: ${{parameters.repoUrl}}
  
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{steps['publish'].output.repoContentsUrl}}
        catalogInfoPath: '/catalog-info.yaml'

    - id: backstage_request
      name: kiuwan
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/secure-development-reporter'
        headers:
          content-type: 'application/json'
        body:
          urlRepository: ${{steps['publish'].output.repoContentsUrl}}
          agileTrain: ${{ parameters.train }}
          agileCell: ${{ parameters.organization }}
          projectName: ${{ parameters.name }}
          microserviceName: ${{ parameters.name }}
          branch: "test"
          internetExposure: ${{ parameters.internet }}
          developmentLanguaje: "java-fuse"    
           
  output:
    links:
      - title: Repository
        url: ${{steps['publish'].output.remoteUrl}}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{steps['register'].output.entityRef}}

