apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - segmento:${{values.segment}}
    - producto:${{values.product}}
    - dom-fun:${{values.fdomain}}
    - integracion:${{values.integration}}
    - lenguaje:java-apache-camel
spec:
  type: ${{values.method}}
  owner: ${{values.cell}}
  lifecycle: production
  system: integracion-ocp
  definition: 
    $text: /docs/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - segmento:${{values.segment}}
    - producto:${{values.product}}
    - dom-fun:${{values.fdomain}}
    - integracion:${{values.integration}}
    - lenguaje:java-apache-camel
spec:
  type: service
  owner: ${{values.cell}}
  lifecycle: production
  system: integracion-ocp
  dependsOn:
    - ${{values.legacy}}
  providesApis:
    - ${{values.name}}
  apiConsumedBy: 
    - ${{values.channels}}
  
