apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - segmento-${{values.segment}}
    - producto-${{values.product}}
    - dom-funcional-${{values.fdomain}}
    - integration-${{values.integration}}
    - lenguaje-java-apache-camel
spec:
  type: openapi
  owner: ${{values.organization}}
  lifecycle: production
  system: PlataformaDeContenedores
  definition: 
    $text: /docs/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - segmento:${{values.segment}}
    - producto:${{values.product}}
    - dom-funcional:${{values.fdomain}}
    - integration:${{values.integration}}
    - lenguaje:java-apache-camel
spec:
  type: service
  owner: ${{values.organization}}
  lifecycle: production
  system: PlataformaDeContenedores
  dependsOn:
    - ${{values.platform}}
    - ${{values.destination}}
  providesApis:
    - ${{values.name}}
  apiConsumedBy: 
    - ${{values.consumer}}

